
;
; Asterisk Call Management support
;

; By default asterisk will listen on localhost only. 
[general]
enabled = yes
port = 5038
bindaddr = 127.0.0.1
webenabled = no


[alertapi]
secret = pass1234
read = system,call,log,verbose,command,agent,user
write = system,call,log,verbose,command,agent,user

; No access is allowed by default.
; To set a password, create a file in /etc/asterisk/manager.d
; use creative permission games to allow other serivces to create their own
; files
#include "manager.d/*.conf" 

